/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "error_messages": {
        "API_KEY_MISSING": string;
        "API_KEY_INVALID": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
